# Generated by Django 5.0.9 on 2026-02-10 15:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100, unique=True)),
                ('default_hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'ordering': ['role_name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('client_name', models.CharField(max_length=255)),
                ('budget_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_invoice_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_margin', models.DecimalField(decimal_places=2, help_text='Margen objetivo en porcentaje, ej: 30.00', max_digits=5)),
                ('jira_project_key', models.CharField(blank=True, default='', max_length=20)),
                ('clockify_project_id', models.CharField(blank=True, default='', max_length=100)),
                ('current_health_status', models.CharField(choices=[('CRITICAL', 'Critical'), ('WARNING', 'Warning'), ('HEALTHY', 'Healthy')], default='HEALTHY', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('estimated_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='finance.project')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProjectHealthAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('CRITICAL', 'Critical'), ('WARNING', 'Warning')], max_length=10)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='finance.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('consumption_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('progress_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('budget_consumed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('earned_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('health_status', models.CharField(max_length=10)),
                ('health_score', models.IntegerField(default=50, help_text='0-100 para Gauge Chart')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to='finance.project')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['project', 'timestamp'], name='finance_hea_project_145dea_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectRoleRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('billing_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.billingrole')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_rates', to='finance.project')),
            ],
            options={
                'unique_together': {('project', 'billing_role')},
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clockify_id', models.CharField(max_length=100, unique=True)),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True, default='')),
                ('duration_hours', models.DecimalField(decimal_places=4, max_digits=8)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('date', models.DateField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('billing_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.billingrole')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='finance.phase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='finance.project')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['project', 'date'], name='finance_tim_project_98ae0e_idx')],
            },
        ),
    ]
