# Generated by Django 5.0.9 on 2026-02-18 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_org',
            field=models.ForeignKey(blank=True, help_text='The external client organization that owns this project.', limit_choices_to={'org_type': 'EXTERNAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='accounts.organization'),
        ),
    ]
