# Generated by Django 5.0.9 on 2026-02-18 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_phase_status_sprints'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='finance.sprint'),
        ),
    ]
