# Generated by Django 5.0.9 on 2026-02-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_add_sprint_to_timeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
