# Generated by Django 5.0.9 on 2026-02-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_add_invoice_file_to_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='anticipo_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto del anticipo recibido', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='anticipo_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='anticipo_file',
            field=models.FileField(blank=True, null=True, upload_to='anticipos/'),
        ),
    ]
