# Generated by Django 5.0.9 on 2026-03-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_project_is_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='internal_category',
            field=models.CharField(blank=True, choices=[('DAILYS', 'Dailys / Reuniones'), ('VENTAS', 'Ventas'), ('CAPACITACION', 'Capacitación'), ('INNOVACION', 'Innovación / Data'), ('HR_ADMIN', 'RH y Admin'), ('GESTION', 'Gestión PMO'), ('TI', 'TI / Desarrollo Interno'), ('DISENO', 'Diseño Interno'), ('OTHER', 'Otro')], default='', help_text='Categoría para proyectos internos (vacío = proyecto cliente).', max_length=20),
        ),
    ]
